name: nightly
on:
  schedule:
  - cron: "0 12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B -DskipTests=true -DskipITs=true install
    - name: Publish SNAPSHOTS to oss.sonatype.org
      run: mvn --no-transfer-progress -B -DskipTests=true deploy
      env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
